dict["Colorado"] = [
  { name: "seafood", count: 3, avg_rating: 4.0 },
  { name: "chicken", count: 2, avg_rating: 3.5 },
  { name: "sauce", count: 2, avg_rating: 3.5 },
  { name: "rice", count: 2, avg_rating: 5.0 },
  { name: "honey", count: 1, avg_rating: 5.0 },
  { name: "tater", count: 1, avg_rating: 2.0 },
  { name: "earl", count: 1, avg_rating: 2.0 },
  { name: "prawn", count: 1, avg_rating: 2.0 },
  { name: "pancake", count: 1, avg_rating: 2.0 },
  { name: "cutlet", count: 1, avg_rating: 5.0 },
  { name: "gnocchi", count: 1, avg_rating: 5.0 },
  { name: "duck", count: 1, avg_rating: 5.0 },
  { name: "salad", count: 1, avg_rating: 5.0 },
  { name: "pudding", count: 1, avg_rating: 5.0 },
  { name: "milk", count: 1, avg_rating: 5.0 },
  { name: "cheese", count: 1, avg_rating: 5.0 },
  { name: "fish", count: 1, avg_rating: 5.0 },
  { name: "salmon", count: 1, avg_rating: 5.0 },
  { name: "bread", count: 1, avg_rating: 5.0 },
  { name: "caramel", count: 1, avg_rating: 5.0 },
  { name: "ale", count: 1, avg_rating: 5.0 },
  { name: "crispy", count: 1, avg_rating: 5.0 },
  { name: "burger", count: 1, avg_rating: 5.0 },
  { name: "fajita", count: 1, avg_rating: 5.0 },
  { name: "pasta", count: 1, avg_rating: 5.0 },
  { name: "power", count: 1, avg_rating: 2.0 },
];
