" NY" : {
    "arepa": [
        [
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                3,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                3,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                3,
                4.666666666666667
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "jH19V2I9fIslnNhDzPmdkA",
                2,
                5.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ]
        ]
    ],
    "beer": [
        [
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                3,
                2.3333333333333335
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ]
        ]
    ],
    "bread": [
        [
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                3,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                1.0
            ]
        ]
    ],
    "breast": [
        [
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                3,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "buffet": [
        [
            [
                "Uz77JHl5e6zlGa-71-6_dA",
                3,
                3.6666666666666665
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ]
        ]
    ],
    "cake": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                3,
                5.0
            ]
        ]
    ],
    "canadian": [
        [
            [
                "0oyzNutZ--rBqP_boeegPg",
                2,
                5.0
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                2,
                3.0
            ],
            [
                "xkha6iK_PLsUqnFB-CJW5g",
                2,
                1.5
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                1,
                5.0
            ]
        ]
    ],
    "carne": [
        [
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                5.0
            ],
            [
                "xkha6iK_PLsUqnFB-CJW5g",
                1,
                1.0
            ],
            [
                "Uz77JHl5e6zlGa-71-6_dA",
                1,
                1.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                1.0
            ]
        ]
    ],
    "cheese": [
        [
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                2,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                2,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "chicken": [
        [
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "Uz77JHl5e6zlGa-71-6_dA",
                1,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                1.0
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                1,
                1.0
            ]
        ]
    ],
    "chip": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "jH19V2I9fIslnNhDzPmdkA",
                1,
                5.0
            ]
        ]
    ],
    "coffee": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                15,
                4.933333333333334
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                2,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "cole": [
        [
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                2,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ],
            [
                "xkha6iK_PLsUqnFB-CJW5g",
                1,
                2.0
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                1,
                1.0
            ]
        ]
    ],
    "cone": [
        [
            [
                "0oyzNutZ--rBqP_boeegPg",
                4,
                5.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                1,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                5.0
            ]
        ]
    ],
    "cream": [
        [
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                3,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "daddy": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "durian": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ]
        ]
    ],
    "earl": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ],
            [
                "jH19V2I9fIslnNhDzPmdkA",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                1,
                1.0
            ]
        ]
    ],
    "egg": [
        [
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                2,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                1,
                5.0
            ]
        ]
    ],
    "elote": [
        [
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                3,
                5.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                2,
                5.0
            ],
            [
                "Uz77JHl5e6zlGa-71-6_dA",
                2,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ]
        ]
    ],
    "flavour": [
        [
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                2,
                3.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                1,
                1.0
            ]
        ]
    ],
    "french": [
        [
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ],
            [
                "jH19V2I9fIslnNhDzPmdkA",
                1,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                5.0
            ]
        ]
    ],
    "fried": [
        [
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                2,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                2,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                1,
                5.0
            ],
            [
                "Uz77JHl5e6zlGa-71-6_dA",
                1,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "guinness": [
        [
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                2,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "hash": [
        [
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                2,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "hot": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "Uz77JHl5e6zlGa-71-6_dA",
                1,
                5.0
            ]
        ]
    ],
    "leek": [
        [
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                5.0
            ]
        ]
    ],
    "lime": [
        [
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                2,
                5.0
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                2,
                3.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                1,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                5.0
            ]
        ]
    ],
    "onion": [
        [
            [
                "0oyzNutZ--rBqP_boeegPg",
                2,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                2,
                3.5
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                2,
                1.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ]
        ]
    ],
    "parm": [
        [
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                3,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                5.0
            ]
        ]
    ],
    "pie": [
        [
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "jH19V2I9fIslnNhDzPmdkA",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "pinot": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                4.5
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                5.0
            ]
        ]
    ],
    "pizza": [
        [
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                7,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                5,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                5.0
            ]
        ]
    ],
    "porter": [
        [
            [
                "Uz77JHl5e6zlGa-71-6_dA",
                2,
                3.0
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                2,
                1.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                5.0
            ],
            [
                "jH19V2I9fIslnNhDzPmdkA",
                1,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                1.0
            ]
        ]
    ],
    "poutine": [
        [
            [
                "0oyzNutZ--rBqP_boeegPg",
                2,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                2,
                3.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                3.0
            ]
        ]
    ],
    "punch": [
        [
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                2,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                2,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                1,
                1.0
            ]
        ]
    ],
    "rice": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                4,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                4,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                3,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                2,
                5.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                2,
                5.0
            ],
            [
                "Uz77JHl5e6zlGa-71-6_dA",
                2,
                3.0
            ],
            [
                "jH19V2I9fIslnNhDzPmdkA",
                1,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                1.0
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                1,
                1.0
            ]
        ]
    ],
    "ring": [
        [
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                2,
                3.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "salad": [
        [
            [
                "0oyzNutZ--rBqP_boeegPg",
                2,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                5.0
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                1,
                1.0
            ]
        ]
    ],
    "sandwich": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                1,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "sauce": [
        [
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                2,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                2,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                1,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                5.0
            ]
        ]
    ],
    "seafood": [
        [
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                5,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                4,
                5.0
            ],
            [
                "jH19V2I9fIslnNhDzPmdkA",
                4,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                3,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                3,
                5.0
            ],
            [
                "Uz77JHl5e6zlGa-71-6_dA",
                3,
                3.6666666666666665
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                3,
                2.3333333333333335
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                2,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                2,
                3.0
            ]
        ]
    ],
    "soda": [
        [
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                2,
                3.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                2.0
            ]
        ]
    ],
    "soup": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ],
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "sprout": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ]
        ]
    ],
    "steak": [
        [
            [
                "BmZu5ackYYCrgQIaJ3-r9A",
                2,
                1.5
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "jH19V2I9fIslnNhDzPmdkA",
                1,
                5.0
            ]
        ]
    ],
    "tater": [
        [
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "jH19V2I9fIslnNhDzPmdkA",
                1,
                5.0
            ],
            [
                "sY2TrIpQaS8kFDI8GRGS3Q",
                1,
                1.0
            ]
        ]
    ],
    "tea": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "6ipr7nnwrzf_o3MGD-8nlA",
                1,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                1,
                5.0
            ]
        ]
    ],
    "wagyu": [
        [
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ],
            [
                "f5Pg89x-2xek78E9KHMhNg",
                1,
                5.0
            ],
            [
                "Uz77JHl5e6zlGa-71-6_dA",
                1,
                1.0
            ],
            [
                "LbM7p-cI0dUCkaUzOyFMTw",
                1,
                1.0
            ]
        ]
    ],
    "wine": [
        [
            [
                "f5Pg89x-2xek78E9KHMhNg",
                2,
                5.0
            ],
            [
                "0oyzNutZ--rBqP_boeegPg",
                2,
                5.0
            ],
            [
                "-Rw3wxbeHhZy6SURriXZ8g",
                1,
                5.0
            ]
        ]
    ]
};